# Generated by Django 3.1.2 on 2020-11-27 12:25

from django.db import migrations, models
import texthandwritten.models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandwritten', '0002_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritten',
            name='textfile',
            field=models.FileField(upload_to=texthandwritten.models.handwritten.update),
        ),
    ]
