# Generated by Django 3.1.2 on 2020-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandwritten', '0003_auto_20201127_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='texthand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=10000)),
            ],
        ),
    ]
