# Generated by Django 2.2.12 on 2020-11-28 18:01

from django.db import migrations, models
import texthandwritten.models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandwritten', '0004_texthand'),
    ]

    operations = [
        migrations.AddField(
            model_name='texthand',
            name='pdffile',
            field=models.FileField(default='default.pdf', upload_to=texthandwritten.models.texthand.update),
        ),
    ]
