# Generated by Django 2.2.12 on 2020-11-28 19:29

from django.db import migrations, models
import texthandwritten.models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandwritten', '0005_texthand_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texthand',
            name='pdffile',
            field=models.FileField(default='outputs/output.pdf', upload_to=texthandwritten.models.texthand.update),
        ),
    ]
