# Generated by Django 3.1.2 on 2020-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandwritten', '0006_auto_20201128_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texthand',
            name='pdffile',
            field=models.FileField(default='outputs/output.pdf', upload_to=''),
        ),
    ]
