# Generated by Django 3.1.2 on 2020-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inpimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpimg',
            name='inp_img',
            field=models.FileField(upload_to='images/2.jpg'),
        ),
    ]
