# Generated by Django 3.1.2 on 2020-11-27 11:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpimg',
            name='inp_img',
            field=models.FileField(upload_to=app.models.inpimg.update),
        ),
    ]
