# Generated by Django 3.1.2 on 2020-11-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201127_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpimg',
            old_name='inp_img',
            new_name='image',
        ),
    ]
