# Generated by Django 3.1.2 on 2020-11-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201127_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpimg',
            old_name='image',
            new_name='inp_img',
        ),
    ]
