# Generated by Django 3.1.2 on 2020-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ratereviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='grammarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('grammar', models.TextField()),
            ],
        ),
    ]
