# Generated by Django 3.1.2 on 2020-12-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_grammarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
